application: lamplight-1248
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /static/css
  static_dir: static/css

- url: /static/fonts
  static_dir: static/fonts

- url: /static/images
  static_dir: static/images

- url: /static/js
  static_dir: static/js

- url: /static/js/typeahead.js
  static_dir: static/js/typeahead.js

- url: /static/js/Jit
  static_dir: static/js/Jit


- url: /favicon\.ico
  static_files: static/images/icon.png
  upload: favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"